/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AppLocalePicker: typeof import('./components/Application/src/AppLocalePicker.vue')['default']
    AppLogo: typeof import('./components/Application/src/AppLogo.vue')['default']
    AppProvider: typeof import('./components/Application/src/AppProvider.vue')['default']
    CountButton: typeof import('./components/Countdown/src/CountButton.vue')['default']
    CountdownInput: typeof import('./components/Countdown/src/CountdownInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
